name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Gradlew 실행 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # 3. [수정] JDK 17로 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # 11 -> 17
          distribution: 'temurin'

      # 4. [수정] env.properties 대신 application.properties 생성
      - name: Create application.properties
        run: |
          echo "Creating application.properties"
          mkdir -p ./src/main/resources 
          echo "${{ secrets.ENV }}" > ./src/main/resources/application.properties
        shell: bash

      # 5. [수정] Gradle build (Test 포함, 액션 버전 v3로 업그레이드)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build

      # [ 추가 ] Docker Hub에 로그인하는 스텝
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. [수정] Docker 이미지 빌드, 태그, 푸시를 한 번에 처리
      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-deep-dive:${GITHUB_SHA::7} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-deep-dive:${GITHUB_SHA::7}